= Updates included in Chronicle Map 3
Neil Clifford
:toc: macro
:toclevels: 1
:css-signature: demo
:toc-placement: macro
:icons: font

toc::[]

Changes between Chronicle Map 3 and the previous Chronicle Map version are detailed below:

== Functional changes

 - Chronicle Map 3 has link::https://github.com/OpenHFT/Chronicle-Map/blob/doco_refresh/spec[formal data store specification] that specifies link::https://github.com/OpenHFT/Chronicle-Map/blob/doco_refresh/spec/1-design-goals.md#guarantees-1[the guarantees
 which the data store provides] and gives a way to verify those guarantees.

 - Added support for multi-key queries.

 - "Listeners" mechanism fully reworked; see <<CM_Tutorial_Behaviour.adoc#,Behaviour Customization>>. This has a number of important consequences, most notable is:

 ** it is now possible to define "eventual-consistency" replication strategy, different from "last write wins"; any state-based CRDT.

 - "Stateless clients" functionality (remote calls) is moved to https://github.com/OpenHFT/Chronicle-Engine[Chronicle Engine].

 - Replication is performed using https://github.com/OpenHFT/Chronicle-Engine[Chronicle Engine].

 - Earlier versions of Chronicle Map had hard creation-time limits on the number of entries storable in a Chronicle Map. If the size exceeded this limit, an exception is thrown. +
 In Chronicle Map 3, this limitation is removed. The number of entries still has to be configured when the Chronicle Map is created, Exceeding this configured limit is possible, but discouraged. +
 For more information, see the <<Configure `.entries(entries)`>> section.

 - Chronicle Map 3 supports <<CM_Tutorial.adoc#entry-checksums,entry checksums>> that enables detection of  data corruption, providing additional safety.

 - Chronicle Map 3 allows <<CM_Tutorial.adoc#Recovery,recovery>> after failures and corruptions.

 - Minor improvements and fixes.

== Non-functional changes

 - Chronicle Map 3 requires Java version 8, or newer.

 - Chronicle Map 3 has <<CM_Versioning.adoc#, versioning policy>> and <<CM_Compatibility.adoc#,compatibility policy>>.


'''
<<../ReadMe.adoc#,Back to ReadMe>>
